### ISSUE TITLE
Molecule (3) in using ansible-devel: ModuleNotFoundError: No module named 'ansible.module_utils.docker'

### ISSUE THREAD

**Issue by robertdebock** [ansible-community/molecule#2626]
# Issue Type

- Bug report

# Molecule and Ansible details

```
Ansible: git+https://github.com/ansible/ansible.git@devel
molecule: molecule>=3, <4
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

- ansible-lint (latest)

# Desired Behavior

Tests succeed.

# Actual Behaviour

I guess Ansible (devel branch) [does not contain all modules anymore](https://github.com/ansible-collections/overview#timeline), and since a few days molecule fails.

See [the example build](https://travis-ci.org/github/robertdebock/ansible-role-xinetd/jobs/666179745#L314)

```
--> Sanity checks: 'docker'
Traceback (most recent call last):
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/molecule/command/test.py", line 147, in test
    base.execute_cmdline_scenarios(scenario_name, args, command_args)
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/molecule/command/base.py", line 109, in execute_cmdline_scenarios
    execute_scenario(scenario)
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/molecule/command/base.py", line 151, in execute_scenario
    execute_subcommand(scenario.config, action)
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/molecule/command/base.py", line 140, in execute_subcommand
    return command(config).execute()
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/molecule/command/destroy.py", line 107, in execute
    self._config.provisioner.destroy()
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/molecule/provisioner/ansible.py", line 681, in destroy
    pb.execute()
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/molecule/provisioner/ansible_playbook.py", line 98, in execute
    self._config.driver.sanity_checks()
  File "/home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/lib/python3.7/site-packages/molecule/driver/docker.py", line 222, in sanity_checks
    from ansible.module_utils.docker.common import HAS_DOCKER_PY
ModuleNotFoundError: No module named 'ansible.module_utils.docker'
ERROR: InvocationError for command /home/travis/build/robertdebock/ansible-role-xinetd/.tox/py37-ansible-next/bin/molecule test (exited with code 1)
```

This error seems to come from [this file/line](https://github.com/ansible-community/molecule/blob/master/molecule/driver/docker.py#L222).

Maybe I need to change something, please give me a hint.

As always, thanks!

**Comment by ssbarnea** [comment]
Fixed on master.
