### ISSUE TITLE
Molecule not installing with ImportError: No module named 'click_completion'

### ISSUE THREAD

**Issue by geerlingguy** [ansible-community/molecule#2810]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.9.12
molecule 3.0.2.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

When I install Molecule, it should install successfully.

# Actual Behaviour

I install Molecule (along with other Python deps) like this:

```
pip3 install ansible molecule ansible-lint yamllint docker
```

But during install it seems to install a much older version (3.0.2.1) and I get an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 5, in <module>
    from molecule.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/molecule/__main__.py", line 22, in <module>
    from molecule.shell import main
  File "/usr/local/lib/python3.5/dist-packages/molecule/shell.py", line 23, in <module>
    import click_completion
ImportError: No module named 'click_completion'
```

I'm seeing some other strange install errors on some of my other CI jobs (but not all, which makes this more puzzling), so I'm going to try to see if there was some other Python package that everything depends on which started failing today...

**Comment by geerlingguy** [comment]
It looks like this was not the fault of molecule, but rather some dependency/environment issue in Ubuntu 18.04's Python 3 build. 

I had to switch my Travis CI build environments to use Focal Fossa (20.04), and now the errors I was seeing (in addition to the error above, I was getting `error: invalid command 'bdist_wheel'` in other builds) are gone.
