### ISSUE TITLE
molecule 3.2.x will not execute

### ISSUE THREAD

**Issue by jamesla** [ansible-community/molecule#3005]
But when using molecule 3.2.x

Works fine with < 3.1.5

```
[I] 10:17:18 ➜  molecule molecule --version
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 6, in <module>
    from molecule.__main__ import main
  File "/usr/local/lib/python3.7/dist-packages/molecule/__main__.py", line 22, in <module>
    from molecule.shell import main
  File "/usr/local/lib/python3.7/dist-packages/molecule/shell.py", line 29, in <module>
    from molecule import command
  File "/usr/local/lib/python3.7/dist-packages/molecule/command/__init__.py", line 27, in <module>
    from molecule.command import base  # noqa
  File "/usr/local/lib/python3.7/dist-packages/molecule/command/base.py", line 32, in <module>
    import molecule.scenarios
  File "/usr/local/lib/python3.7/dist-packages/molecule/scenarios.py", line 23, in <module>
    from molecule import logger, util
  File "/usr/local/lib/python3.7/dist-packages/molecule/logger.py", line 29, in <module>
    from enrich.console import Console
  File "/usr/local/lib/python3.7/dist-packages/enrich/console.py", line 8, in <module>
    from rich.ansi import AnsiDecoder
ModuleNotFoundError: No module named 'rich.ansi'
```

**Comment by dvzrv** [comment]
Do you have [rich](https://pypi.org/project/rich/) installed? How did you install molecule?

**Comment by apatard** [comment]
hm. weird. the dependency tree is molecule -> enrich -> rich. molecule and enrich are installed, so rich should be installed too. What might be the problem would be rich being too old (so without rich.ansi) but enrich is depending correctly on rich >= 9.2.0 to avoid that...
