### ISSUE TITLE
[DOC] Example for testinfra verifier is wrong

### ISSUE THREAD

**Issue by hunter86bg** [ansible-community/molecule#3028]
# Issue Type
- Bug report

# Molecule and Ansible details

```
(molecule32_ansible2910_py36) [user@server bin]$ ansible --version
ansible 2.9.10
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/ansible
  executable location = /opt/somepath/venvs/molecule32_ansible2910_py36/bin/ansible
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
(molecule32_ansible2910_py36) [user@server bin]$ molecule --version
molecule 3.2.0 using python 3.6
    ansible:2.9.10
    delegated:3.2.0 from molecule
    vagrant:0.6 from molecule_vagrant
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

Detail any linters or test runners used:
```
verifier:
  name: testinfra
  lint: |
    set -e
    yamllint -c .yamllint .
  options:
    n: 1
```
# Desired Behavior

The example in the documentation to work

# Actual Behaviour
```
Traceback (most recent call last):
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/molecule/command/test.py", line 148, in test
    base.execute_cmdline_scenarios(scenario_name, args, command_args)
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/molecule/command/base.py", line 112, in execute_cmdline_scenarios
    execute_scenario(scenario)
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/molecule/command/base.py", line 154, in execute_scenario
    execute_subcommand(scenario.config, action)
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/molecule/command/base.py", line 143, in execute_subcommand
    return command(config).execute()
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/molecule/logger.py", line 187, in wrapper
    rt = func(*args, **kwargs)
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/molecule/command/verify.py", line 73, in execute
    self._config.verifier.execute()
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/molecule/verifier/testinfra.py", line 184, in execute
    result = util.run_command(self._testinfra_command, debug=self._config.debug)
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/molecule/util.py", line 143, in run_command
    args, env=env, stdout=stdout, stderr=stderr, echo=echo or debug, quiet=quiet
  File "/opt/somepath/venvs/molecule32_ansible2910_py36/lib64/python3.6/site-packages/subprocess_tee/__init__.py", line 103, in run
    cmd = join(args)
  File "/usr/lib64/python3.6/subprocess.py", line 481, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable
```

**Comment by abtreece** [comment]
@hunter86bg can you link to the incorrect docs?

I believe that yaml should be:

```
verifier:
  name: testinfra
lint: |
  set -e
  yamllint -c .yamllint .
```

**Comment by hunter86bg** [comment]
I think the link was: https://molecule.readthedocs.io/en/latest/configuration.html#molecule.verifier.testinfra.Testinfra
