### ISSUE TITLE
Molecule verify can't find testinfra module.

### ISSUE THREAD

**Issue by juju2112** [ansible-community/molecule#3044]
# Issue Type

- Bug report

# Molecule and Ansible details

Whenever I try to run `verify`, I get:

```
(venv) donald@laptop:~/src/graylog-ansible-role$ molecule verify --scenario-name=ui     
INFO     ui scenario test matrix: verify
INFO     Running ui > verify
INFO     Executing Testinfra tests found in /home/donald/src/graylog-ansible-role/molecule/ui/tests/...
Traceback (most recent call last):
  File "/home/donald/src/graylog-ansible-role/venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1280, in parse
    self._preparse(args, addopts=addopts)
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'testinfra.plugin'

```

Here are the versions of things I am running:

```
(venv) donald@laptop:~/src/graylog-ansible-role$ ansible --version && molecule --version
ansible 2.10.1
  config file = /home/donald/.ansible.cfg
  configured module search path = ['/home/donald/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages/ansible
  executable location = /home/donald/src/graylog-ansible-role/venv/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
molecule 3.2.3 using python 3.8 
    ansible:2.10.1
    delegated:3.2.3 from molecule
    docker:0.2.4 from molecule_docker
    podman:0.3.0 from molecule_podman
    vagrant:0.6 from molecule_vagrant
(venv) donald@laptop:~/src/graylog-ansible-role$ pip3 show testinfra
Name: testinfra
Version: 6.0.0
Summary: Test infrastructures
Home-page: https://github.com/philpep/testinfra
Author: Philippe Pepiot
Author-email: phil@philpep.org
License: UNKNOWN
Location: /home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages
Requires: pytest-testinfra
Required-by: 
(venv) donald@laptop:~/src/graylog-ansible-role$ pip3 show pytest-testinfra
Name: pytest-testinfra
Version: 6.1.0
Summary: Test infrastructures
Home-page: https://github.com/pytest-dev/pytest-testinfra
Author: Philippe Pepiot
Author-email: phil@philpep.org
License: UNKNOWN
Location: /home/donald/src/graylog-ansible-role/venv/lib/python3.8/site-packages
Requires: pytest
Required-by: testinfra
(venv) donald@laptop:~/src/graylog-ansible-role$ cat requirements.txt
ansible==2.10.0
ansible-base==2.10.1
ansible-lint==4.3.5
chromedriver-binary-auto==0.1
enrich==1.2.6
molecule==3.2.3
molecule-docker==0.2.4
molecule-podman==0.3.0
molecule-vagrant==0.6
python-vagrant==0.5.15
pytest-testinfra==6.1.0
selenium==3.141.0
yamllint==1.25.0
wheel
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:
My molecule.yml looks like:

```
---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    ignore-errors: true
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: ${MOLECULE_DISTRO:-generic/ubuntu2004}
    memory: 4096
    cpus: 1
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 9000"
      - "vm.network 'forwarded_port', guest: 12201, host: 12201, protocol: 'udp'"
provisioner:
  name: ansible
verifier:
 name: testinfra
 options:
   s: true
```

# Desired Behavior

It used to run my tests, and now it doesn't. 

# Actual Behaviour

Running `molecule verify` throws this error:

`ModuleNotFoundError: No module named 'testinfra.plugin'`

I know that the `testinfra` module was recently renamed to `pytest-testinfra`. But having one or both named modules installed doesn't make the error disappear.

**Comment by abtreece** [comment]
Hey @juju2112... I having a similar issue. I resolved it by uninstalling both `testinfra` and `pytest-testinfra` and then reinstalling `pytest-testinfra`.

**Comment by juju2112** [comment]
@abtreece That worked, thank you! 

Fairly simple troubleshooting. I should have thought of it!
