### ISSUE TITLE
Support Ansible Debug Mode

### ISSUE THREAD

**Issue by jimbo8098** [ansible-community/molecule#3082]
# Issue Type

- Feature request

# Molecule and Ansible details

```
761917 1616519124.85984: starting run
ansible 2.10.7
  config file = /home/jimspeir/.ansible.cfg
  configured module search path = ['/home/jimspeir/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jimspeir/.local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]



763930 1616519359.71985: starting run
ansible 2.10.7
  config file = /home/jimspeir/.ansible.cfg
  configured module search path = ['/home/jimspeir/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jimspeir/.local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python3/dist-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1089, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1476, in handle_parse_result
    value = invoke_param_callback(
  File "/usr/lib/python3/dist-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/jimspeir/.local/lib/python3.8/site-packages/molecule/shell.py", line 66, in print_version
    f"    [repr.attrib_name]ansible[/][dim]:[/][repr.number]{ansible_version()}[/]"
  File "/home/jimspeir/.local/lib/python3.8/site-packages/molecule/config.py", line 477, in ansible_version
    return Version(version)
  File "/usr/local/lib/python3.8/dist-packages/packaging/version.py", line 298, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: '1616519360.39662:'
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

# Desired Behavior

When you output the version number with ansible.cfg's `debug=true` (as above) the ansible build reference is output which throws off version checks on https://github.com/ansible-community/molecule/blob/60b68140fb5c650c47019f5db238c0864dbd43ed/src/molecule/config.py#L484  I propose that the check might include a check for the word ansible which seems consistent. If that's an agreed handling of this, I'm happy to PR a change.

When `debug=false`, the issue immediately goes away because the version check passes.

**Comment by tadeboro** [comment]
An alternative approach to solving this problem is to run the `ansible --version` command with the `ANSIBLE_DEBUG` environment variable set to `0`. Any approach is fine with me, but I would prefer the environment variable route because controlling the environment seems easier than parsing the n variants of output that are not meant for machine consumption.

**Comment by tadeboro** [comment]
I did look into this a bit more and parsing that version number is not really needed. Maybe we should just get rid of it for good?
