### ISSUE TITLE
molecule requires symlinks in current version to work (previous versions worked fine)

### ISSUE THREAD

**Issue by dlevene1** [ansible-community/molecule#3123]
# Issue Type

- Bug report

# Molecule and Ansible details

```
 molecule --version && ansible --version
molecule 3.3.1 using python 3.6
    ansible:2.10.3
    delegated:3.3.1 from molecule
    docker:0.3.3 from molecule_docker
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behaviour

Previous versions of molecule worked fine. Not sure which version was running, sorry, but when running standard molecule tests things were ok, now i'm hitting an issue where I can't run them due to it wanting to create symlinks (which are not allowed in my setup)

When I copy the role to a spot where symlinks are allowed it works.

`INFO     Using .cache/roles/role_name symlink to current repository in order to enable Ansible to find the role using its expected full name.`

I would like to be able to run this without creating a symlink.

While I can review making future changes and change my way of working, it did work in the past, hence raising this bug report.

# Actual Behaviour

Please give some details of what is actually happening.
```
$ molecule --debug lint
DEBUG    Validating schema /git_repos/myrolename/molecule/default/molecule.yml.
INFO     default scenario test matrix: dependency, lint
INFO     Performing prerun...
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/molecule/command/lint.py", line 120, in lint
    base.execute_cmdline_scenarios(scenario_name, args, command_args)
  File "/usr/local/lib/python3.6/site-packages/molecule/command/base.py", line 112, in execute_cmdline_scenarios
    prepare_environment()
  File "/home/levenda/.local/lib/python3.6/site-packages/ansiblelint/prerun.py", line 172, in prepare_environment
    _install_galaxy_role()
  File "/home/levenda/.local/lib/python3.6/site-packages/ansiblelint/prerun.py", line 254, in _install_galaxy_role
    link_path.symlink_to(pathlib.Path("../..", target_is_directory=True))
  File "/usr/lib64/python3.6/pathlib.py", line 1327, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "/usr/lib64/python3.6/pathlib.py", line 434, in symlink
    return os.symlink(str(a), str(b))
PermissionError: [Errno 1] Operation not permitted: '../..' -> '.cache/roles/myrolename'
```

**Comment by tadeboro** [comment]
This preparation step was introduced in molecule 3.3.0 IIRC, so the simplest thing to do right now to get things running again is to downgrade your molecule to pre-3.3. For pip, you can run something like `pip install -U 'molecule<3.3'`.

Not sure what is the best way forward here since I must admit I forgot what was the reasoning behind the prerun introduction.

**Comment by dlevene1** [comment]
Thanks tadeboro.

I ended up having to do this 
-U 'ansible-lint<5.0' -U 'molecule<3.3'

Would be good to know a little more about it? My situation is my company provides me a windows host to perform development on so i'm sharing a windows drive via virtual box persistent shared folders and running linux in there. the filesystem works as normal.. just doesn't allow symlinks. I could setup vs code with the ssh client running - or setup some kind of NFS share and share it back to windows.. so there are options for me but this allows me to share the same filesystem across many virtual machines without actually doing anything extra and work natively on my windows desktop.

Also note that i'm running molecule from a docker instance, just sharing the role in at the correct spots - so running different versions is easy too.

Did a bit more digging and found this
https://github.com/ansible-community/ansible-lint/blob/master/docs/usage.rst#temporary-files

and pointing to the current code here..
https://github.com/ansible-community/ansible-lint/blob/master/src/ansiblelint/prerun.py#L254

I think the solution here is to be able to define the temp dir - if I manually create it.. it works - but i'm sure its not doing what it should do, nor what the impacts might be.
$ mkdir -p .cache/roles/myrolename
$ molecule lint

Should I raise something against the ansible-lint repo?

**Comment by tadeboro** [comment]
No need to file new things, I will just move this issue to the ansible-lint repo since the issue is only partially related to the molecule and the main culprit is the code in ansible-lint that the molecule uses.
