### ISSUE TITLE
Can't run molecule because python error

### ISSUE THREAD

**Issue by Jonas18175** [ansible-community/molecule#3157]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible [core 2.11.1] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.5 (default, May 24 2021, 12:50:35) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True
molecule 3.3.1 using python 3.9 
    ansible:2.11.1
    delegated:3.3.1 from molecule
    docker:0.3.3a1 from molecule_docker
    podman:0.3.0 from molecule_podman
    vagrant:0.2 from molecule_vagrant

```

System:
Linux jonas-pc 5.10.36-2-MANJARO #1 SMP PREEMPT Tue May 11 19:38:44 UTC 2021 x86_64 GNU/Linux

Molecule installation method (one of):

- pip
- and tried with OS package

Ansible installation method (one of):

- OS package

Detail any linters or test runners used:

# Desired Behavior

Running without python stacktrace.

# Actual Behaviour

```
DEBUG    Validating schema /home/jonas/_dev/my-playbook/roles/docker/molecule/default/molecule.yml.
INFO     default scenario test matrix: lint, destroy, syntax, create, prepare, converge, idempotence, verify, destroy
INFO     Running default > lint
COMMAND: set -e
yamllint .
ansible-lint .
Loading custom .yamllint config file, this extends our internal yamllint config.
WARNING  Listing 1 violation(s) that are fatal
load-failure: [Errno 2] No such file or directory: 'tasks/package_manager/general.yml' (filenotfounderror)
tasks/package_manager/general.yml:1


Finished with 0 failure(s), 1 warning(s) on 25 files.
INFO     Running default > destroy
Traceback (most recent call last):
  File "/home/jonas/.local/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/command/test.py", line 149, in test
    base.execute_cmdline_scenarios(scenario_name, args, command_args)
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/command/base.py", line 113, in execute_cmdline_scenarios
    execute_scenario(scenario)
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/command/base.py", line 155, in execute_scenario
    execute_subcommand(scenario.config, action)
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/command/base.py", line 144, in execute_subcommand
    return command(config).execute()
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/logger.py", line 185, in wrapper
    rt = func(*args, **kwargs)
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/command/destroy.py", line 107, in execute
    self._config.provisioner.destroy()
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/provisioner/ansible.py", line 702, in destroy
    pb = self._get_ansible_playbook(self.playbooks.destroy)
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/provisioner/ansible.py", line 868, in _get_ansible_playbook
    return ansible_playbook.AnsiblePlaybook(playbook, self._config, **kwargs)
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/provisioner/ansible_playbook.py", line 45, in __init__
    self._env = self._config.provisioner.env
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/provisioner/ansible.py", line 519, in env
    default_env = self.default_env
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/provisioner/ansible.py", line 458, in default_env
    self._config.ansible_collections_path: ":".join(collections_path_list),
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/config.py", line 119, in ansible_collections_path
    if ansible_version() >= ansible_version("2.10.0.dev0"):
  File "/home/jonas/.local/lib/python3.9/site-packages/molecule/config.py", line 477, in ansible_version
    return Version(version)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 298, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: '[core'
```
Used config:
```
---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
#    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
#    - side_effect
    - verify
    - destroy
platforms:
  - name: rhel8
    image: registry.access.redhat.com/ubi8/ubi-init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true

  - name: ubuntu
    image: geerlingguy/docker-ubuntu2004-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
```

**Comment by tadeboro** [comment]
This is a known issue and should be solved in the latest stable version of molecule. Can you please test your setup with version 3.3.4 and report back? Thank you in advance.

**Comment by Jonas18175** [comment]
I tested it. The version 3.3.4 worked for me! Thanks.
