### ISSUE TITLE
First example in Getting-Started Guide does not work properly 

### ISSUE THREAD

**Issue by theguy147** [ansible-community/molecule#3267]
# Issue Type

- Bug report

# Molecule and Ansible details

```bash
$ ansible --version && molecule --version
ansible [core 2.11.5] 
  config file = None
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/vagrant/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/vagrant/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.2
  libyaml = True
INFO     Found config file /home/vagrant/molecule/.config/molecule/config.yml
molecule 3.5.2 using python 3.8 
    ansible:2.11.5
    delegated:3.5.2 from molecule
    docker:1.0.2 from molecule_docker requiring collections: community.docker>=1.8.0
```

Additional Information:

- The test environment used is a clean and up-to-date Vagrantbox 'ubuntu/focal64' (v20211007.0.0).

Molecule installation method (one of):

- pip (also tried installing it from source but that didn't change anything)

Ansible installation method (one of):

- pip

# Desired Behavior

The steps shown in the [Getting-Started Guide](https://molecule.readthedocs.io/en/latest/getting-started.html) should work without errors:

```bash
molecule init role my-new-role --driver-name docker
cd my-new-role/
molecule create
```

# Actual Behaviour

### Error: Computed fully qualified role name of my-new-role does not follow current galaxy requirements

The following error output will be seen when executing `molecule create` according to the documentation:

```bash
$ molecule --debug create
DEBUG    Validating schema /home/vagrant/my-new-role/molecule/default/molecule.yml.
INFO     default scenario test matrix: dependency, create, prepare
INFO     Performing prerun...
INFO     Added ANSIBLE_LIBRARY=/home/vagrant/.cache/ansible-compat/068eef/modules:/home/vagrant/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Added ANSIBLE_COLLECTIONS_PATH=/home/vagrant/.cache/ansible-compat/068eef/collections:/home/vagrant/.ansible/collections:/usr/share/ansible/collections
INFO     Added ANSIBLE_ROLES_PATH=/home/vagrant/.cache/ansible-compat/068eef/roles:/home/vagrant/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
ERROR    Computed fully qualified role name of my-new-role does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.

Traceback (most recent call last):
  File "/home/vagrant/molecule/.venv/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/molecule/.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/molecule/.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/molecule/.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/molecule/.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/molecule/.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/vagrant/molecule/.venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vagrant/molecule/.venv/lib/python3.8/site-packages/molecule/command/create.py", line 121, in create
    base.execute_cmdline_scenarios(scenario_name, args, command_args)
  File "/home/vagrant/molecule/.venv/lib/python3.8/site-packages/molecule/command/base.py", line 111, in execute_cmdline_scenarios
    scenario.config.runtime.prepare_environment()
  File "/home/vagrant/molecule/.venv/lib/python3.8/site-packages/ansible_compat/runtime.py", line 255, in prepare_environment
    self._install_galaxy_role(self.project_dir, ignore_errors=True)
  File "/home/vagrant/molecule/.venv/lib/python3.8/site-packages/ansible_compat/runtime.py", line 396, in _install_galaxy_role
    raise InvalidPrerequisiteError(msg)
ansible_compat.errors.InvalidPrerequisiteError: Computed fully qualified role name of my-new-role does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.
``` 

While I do understand that `my-new-role` is not compliant to "current galaxy requirements" the same error is also shown for the role name: `my_new_role`.

The issue seems to be that both the default `role_name` and `namespace` don't follow these galaxy requirements:
- `role_name` for the example in the documentation would be the directory name which is `my-new-role`
- `namespace` for the example in the documentation would be the `author` and therefore `your name`

Even though, after carefully reading the complete error message and the linked documentation in it, these errors should become clear I think that **the first example** of the Getting-Started Guide should work out-of-the-box. A user that has never used `molecule` before (like myself) might be very confused by this fact. Not sure if others agree but in my opinion either the documentation (to at least include a warning and explanation) or the implementation (of say the default values replacing " " and "-" with "_") should be adjusted.

**Comment by theguy147** [comment]
Closing this again seeing as it's probably not a bug but a documentation issue
