### ISSUE TITLE
Getting Started Docs are Insufficient for Getting Started

### ISSUE THREAD

**Issue by justin-f-perez** [ansible-community/molecule#3381]
# Issue Type

- Bug report

# Molecule and Ansible details

```
❯ python3 --version && ansible --version && molecule --version
Python 3.9.9
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/Users/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/me/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/me/path/to/ansibroken/venv/bin/ansible
  python version = 3.9.9 (main, Nov 21 2021, 03:16:13) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
molecule 3.5.2 using python 3.9
    ansible:2.12.1
    delegated:3.5.2 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
```

Molecule installation method (one of):

- pip (as recommended by the getting started docs)

Ansible installation method (one of):

- pip (as recommended by the getting started docs)

Detail any linters or test runners used:

None

# Desired Behavior

Just trying out molecule, having never used it before. The commands specified in the getting started docs aren't sufficient for someone who is- literally- just getting started. I expect onboarding documentation (especially for a testing package) to run without (unintentional) errors.

Please give some details of the feature being requested or what
should happen if providing a bug report.

# Actual Behaviour

Script:
```
#!/bin/sh
set -x

mkdir ansibroken && cd ansibroken
# create a venv with python >=3.6 https://molecule.readthedocs.io/en/latest/installation.html#requirements
# python3.9 is supported https://github.com/ansible-community/molecule/blob/main/setup.cfg
python3.9 -m venv ./venv && source ./venv/bin/activate
# make sure setuptools is up to date https://molecule.readthedocs.io/en/latest/installation.html#pip
python3 -m pip install --upgrade setuptools
# install ansible, molecule with the docker driver https://molecule.readthedocs.io/en/latest/installation.html#install
python3 -m pip install 'molecule[docker,lint]' 'ansible-core>=2.8'
# do the things the newbie docs tell me to https://molecule.readthedocs.io/en/latest/getting-started.html#creating-a-new-role
molecule --debug init role my_new_role --driver-name docker
# https://molecule.readthedocs.io/en/latest/getting-started.html#run-test-sequence-commands
docker run hello-world
molecule create # CRITICAL 'molecule/default/molecule.yml' glob failed.  Exiting.
cd my_new_role  # that one's easy enough...
molecule create # ERROR Computed fully qualified role name of my_new_role does not follow current galaxy requirements.
# add the debug flag that the issue template tells me to https://github.com/ansible-community/molecule/issues/new?assignees=&labels=bug&template=bug_report.md
molecule --debug create
molecule list
```

```bash
+ mkdir ansibroken
+ cd ansibroken
+ python3.9 -m venv ./venv
+ source ./venv/bin/activate
++ deactivate nondestructive
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n /bin/sh -o -n '' ']'
++ hash -r
++ '[' -n '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/Users/me/path/to/ansibroken/venv
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/opt/homebrew/Caskroom/miniconda/base/condabin:/Users/me/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/me/dev/pdhands/bin:/Users/me/.local/bin:/opt/homebrew/opt/fzf/bin
++ PATH=/Users/me/path/to/ansibroken/venv/bin:/opt/homebrew/Caskroom/miniconda/base/condabin:/Users/me/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/me/dev/pdhands/bin:/Users/me/.local/bin:/opt/homebrew/opt/fzf/bin
++ export PATH
++ '[' -n '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ PS1='(venv) '
++ export PS1
++ '[' -n /bin/sh -o -n '' ']'
++ hash -r
+ python3 -m pip install --upgrade setuptools
Requirement already satisfied: setuptools in ./venv/lib/python3.9/site-packages (59.0.1)
Collecting setuptools
  Using cached setuptools-60.3.1-py3-none-any.whl (953 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.0.1
    Uninstalling setuptools-59.0.1:
      Successfully uninstalled setuptools-59.0.1
Successfully installed setuptools-60.3.1
+ python3 -m pip install 'molecule[docker,lint]' 'ansible-core>=2.8'
Collecting molecule[docker,lint]
  Using cached molecule-3.5.2-py3-none-any.whl (240 kB)
Collecting ansible-core>=2.8
  Using cached ansible-core-2.12.1.tar.gz (7.4 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting cerberus!=1.3.3,!=1.3.4,>=1.3.1
  Using cached Cerberus-1.3.2.tar.gz (52 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting click-help-colors>=0.9
  Using cached click_help_colors-0.9.1-py3-none-any.whl (5.5 kB)
Collecting cookiecutter>=1.7.3
  Using cached cookiecutter-1.7.3-py2.py3-none-any.whl (34 kB)
Collecting enrich>=1.2.5
  Using cached enrich-1.2.6-py3-none-any.whl (8.6 kB)
Collecting paramiko<3,>=2.5.0
  Using cached paramiko-2.9.1-py2.py3-none-any.whl (210 kB)
Collecting PyYAML<6,>=5.1
  Using cached PyYAML-5.4.1-cp39-cp39-macosx_11_0_arm64.whl
Collecting subprocess-tee>=0.3.5
  Using cached subprocess_tee-0.3.5-py3-none-any.whl (8.0 kB)
Collecting Jinja2>=2.11.3
  Using cached Jinja2-3.0.3-py3-none-any.whl (133 kB)
Collecting rich>=9.5.1
  Using cached rich-10.16.2-py3-none-any.whl (214 kB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pluggy<2.0,>=0.7.1
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting click<9,>=8.0
  Using cached click-8.0.3-py3-none-any.whl (97 kB)
Collecting ansible-compat>=0.5.0
  Using cached ansible_compat-0.5.0-py3-none-any.whl (15 kB)
Collecting molecule-docker>=1.0.0
  Using cached molecule_docker-1.1.0-py3-none-any.whl (16 kB)
Collecting pre-commit>=2.10.1
  Using cached pre_commit-2.16.0-py2.py3-none-any.whl (191 kB)
Collecting flake8>=3.8.4
  Using cached flake8-4.0.1-py2.py3-none-any.whl (64 kB)
Collecting yamllint
  Using cached yamllint-1.26.3.tar.gz (126 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting cryptography
  Using cached cryptography-36.0.1-cp36-abi3-macosx_10_10_universal2.whl (4.8 MB)
Collecting resolvelib<0.6.0,>=0.5.3
  Using cached resolvelib-0.5.4-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: setuptools in ./venv/lib/python3.9/site-packages (from cerberus!=1.3.3,!=1.3.4,>=1.3.1->molecule[docker,lint]) (60.3.1)
Collecting binaryornot>=0.4.4
  Using cached binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
Collecting python-slugify>=4.0.0
  Using cached python_slugify-5.0.2-py2.py3-none-any.whl (6.7 kB)
Collecting six>=1.10
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting requests>=2.23.0
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting jinja2-time>=0.2.0
  Using cached jinja2_time-0.2.0-py2.py3-none-any.whl (6.4 kB)
Collecting poyo>=0.5.0
  Using cached poyo-0.5.0-py2.py3-none-any.whl (10 kB)
Collecting pycodestyle<2.9.0,>=2.8.0
  Using cached pycodestyle-2.8.0-py2.py3-none-any.whl (42 kB)
Collecting pyflakes<2.5.0,>=2.4.0
  Using cached pyflakes-2.4.0-py2.py3-none-any.whl (69 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.0.1-cp39-cp39-macosx_10_9_universal2.whl (18 kB)
Collecting docker>=4.3.1
  Using cached docker-5.0.3-py2.py3-none-any.whl (146 kB)
Collecting bcrypt>=3.1.3
  Using cached bcrypt-3.2.0-cp36-abi3-macosx_10_10_universal2.whl (49 kB)
Collecting pynacl>=1.0.1
  Using cached PyNaCl-1.4.0-cp39-cp39-macosx_11_0_arm64.whl
Collecting cffi>=1.12
  Using cached cffi-1.15.0-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
Collecting virtualenv>=20.0.8
  Using cached virtualenv-20.13.0-py2.py3-none-any.whl (6.5 MB)
Collecting identify>=1.0.0
  Using cached identify-2.4.2-py2.py3-none-any.whl (98 kB)
Collecting cfgv>=2.0.0
  Using cached cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting nodeenv>=0.11.1
  Using cached nodeenv-1.6.0-py2.py3-none-any.whl (21 kB)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting pygments<3.0.0,>=2.6.0
  Using cached Pygments-2.11.2-py3-none-any.whl (1.1 MB)
Collecting colorama<0.5.0,>=0.4.0
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.6-py3-none-any.whl (97 kB)
Collecting pathspec>=0.5.3
  Using cached pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Collecting chardet>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting websocket-client>=0.32.0
  Using cached websocket_client-1.2.3-py3-none-any.whl (53 kB)
Collecting arrow
  Using cached arrow-1.2.1-py3-none-any.whl (63 kB)
Collecting text-unidecode>=1.3
  Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.10-py3-none-any.whl (39 kB)
Collecting platformdirs<3,>=2
  Using cached platformdirs-2.4.1-py3-none-any.whl (14 kB)
Collecting distlib<1,>=0.3.1
  Using cached distlib-0.3.4-py2.py3-none-any.whl (461 kB)
Collecting filelock<4,>=3.2
  Using cached filelock-3.4.2-py3-none-any.whl (9.9 kB)
Collecting python-dateutil>=2.7.0
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Using legacy 'setup.py install' for ansible-core, since package 'wheel' is not installed.
Using legacy 'setup.py install' for cerberus, since package 'wheel' is not installed.
Using legacy 'setup.py install' for yamllint, since package 'wheel' is not installed.
Installing collected packages: six, python-dateutil, pycparser, MarkupSafe, urllib3, text-unidecode, pygments, Jinja2, idna, commonmark, colorama, charset-normalizer, chardet, cffi, certifi, arrow, rich, requests, PyYAML, python-slugify, pyparsing, pynacl, poyo, jinja2-time, cryptography, click, binaryornot, bcrypt, websocket-client, subprocess-tee, pluggy, platformdirs, paramiko, packaging, filelock, enrich, distlib, cookiecutter, click-help-colors, cerberus, ansible-compat, virtualenv, toml, pyflakes, pycodestyle, pathspec, nodeenv, molecule, mccabe, identify, docker, cfgv, yamllint, resolvelib, pre-commit, molecule-docker, flake8, ansible-core
    Running setup.py install for cerberus: started
    Running setup.py install for cerberus: finished with status 'done'
    Running setup.py install for yamllint: started
    Running setup.py install for yamllint: finished with status 'done'
    Running setup.py install for ansible-core: started
    Running setup.py install for ansible-core: finished with status 'done'
Successfully installed Jinja2-3.0.3 MarkupSafe-2.0.1 PyYAML-5.4.1 ansible-compat-0.5.0 ansible-core-2.12.1 arrow-1.2.1 bcrypt-3.2.0 binaryornot-0.4.4 cerberus-1.3.2 certifi-2021.10.8 cffi-1.15.0 cfgv-3.3.1 chardet-4.0.0 charset-normalizer-2.0.10 click-8.0.3 click-help-colors-0.9.1 colorama-0.4.4 commonmark-0.9.1 cookiecutter-1.7.3 cryptography-36.0.1 distlib-0.3.4 docker-5.0.3 enrich-1.2.6 filelock-3.4.2 flake8-4.0.1 identify-2.4.2 idna-3.3 jinja2-time-0.2.0 mccabe-0.6.1 molecule-3.5.2 molecule-docker-1.1.0 nodeenv-1.6.0 packaging-21.3 paramiko-2.9.1 pathspec-0.9.0 platformdirs-2.4.1 pluggy-1.0.0 poyo-0.5.0 pre-commit-2.16.0 pycodestyle-2.8.0 pycparser-2.21 pyflakes-2.4.0 pygments-2.11.2 pynacl-1.4.0 pyparsing-3.0.6 python-dateutil-2.8.2 python-slugify-5.0.2 requests-2.27.1 resolvelib-0.5.4 rich-10.16.2 six-1.16.0 subprocess-tee-0.3.5 text-unidecode-1.3 toml-0.10.2 urllib3-1.26.7 virtualenv-20.13.0 websocket-client-1.2.3 yamllint-1.26.3
+ molecule --debug init role my_new_role --driver-name docker
[34mINFO    [0m Initializing new role my_new_role[33m...[0m
[34mNo config file found; using defaults[0m
- Role my_new_role was created successfully
[34mINFO    [0m Initialized role in [35m/Users/me/path/to/ansibroken/[0m[95mmy_new_role[0m successfully.
+ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

+ molecule create
[1;31mCRITICAL[0m [32m'molecule/default/molecule.yml'[0m glob failed.  Exiting.
+ cd my_new_role
+ molecule create
[34mINFO    [0m default scenario test matrix: dependency, create, prepare
[34mINFO    [0m Performing prerun[33m...[0m
[34mINFO    [0m Added [33mANSIBLE_LIBRARY[0m=[35m/Users/me/.cache/ansible-compat/c52416/[0m[95mmodules[0m:[35m/Users/me/.ansible/plugins/[0m[95mmodules[0m:[35m/usr/share/ansible/plugins/[0m[95mmodules[0m
[34mINFO    [0m Added [33mANSIBLE_COLLECTIONS_PATH[0m=[35m/Users/me/.cache/ansible-compat/c52416/[0m[95mcollections[0m:[35m/Users/me/.ansible/[0m[95mcollections[0m:[35m/usr/share/ansible/[0m[95mcollections[0m
[34mINFO    [0m Added [33mANSIBLE_ROLES_PATH[0m=[35m/Users/me/.cache/ansible-compat/c52416/[0m[95mroles[0m:[35m/Users/me/.ansible/[0m[95mroles[0m:[35m/usr/share/ansible/[0m[95mroles[0m:[35m/etc/ansible/[0m[95mroles[0m
[1;31mERROR   [0m Computed fully qualified role name of my_new_role does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: [4;94mhttps://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations[0m
Role: [4;94mhttps://galaxy.ansible.com/docs/contributing/creating_role.html#role-names[0m

As an alternative, you can add [32m'role-name'[0m to either skip_list or warn_list.

Traceback (most recent call last):
  File "/Users/me/path/to/ansibroken/venv/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/molecule/command/create.py", line 121, in create
    base.execute_cmdline_scenarios(scenario_name, args, command_args)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/molecule/command/base.py", line 111, in execute_cmdline_scenarios
    scenario.config.runtime.prepare_environment()
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/ansible_compat/runtime.py", line 255, in prepare_environment
    self._install_galaxy_role(self.project_dir, ignore_errors=True)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/ansible_compat/runtime.py", line 396, in _install_galaxy_role
    raise InvalidPrerequisiteError(msg)
ansible_compat.errors.InvalidPrerequisiteError: Computed fully qualified role name of my_new_role does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.

+ molecule --debug create
[2;37mDEBUG   [0m Validating schema [35m/Users/me/path/to/ansibroken/my_new_role/molecule/default/[0m[95mmolecule.yml.[0m
[34mINFO    [0m default scenario test matrix: dependency, create, prepare
[34mINFO    [0m Performing prerun[33m...[0m
[34mINFO    [0m Added [33mANSIBLE_LIBRARY[0m=[35m/Users/me/.cache/ansible-compat/c52416/[0m[95mmodules[0m:[35m/Users/me/.ansible/plugins/[0m[95mmodules[0m:[35m/usr/share/ansible/plugins/[0m[95mmodules[0m
[34mINFO    [0m Added [33mANSIBLE_COLLECTIONS_PATH[0m=[35m/Users/me/.cache/ansible-compat/c52416/[0m[95mcollections[0m:[35m/Users/me/.ansible/[0m[95mcollections[0m:[35m/usr/share/ansible/[0m[95mcollections[0m
[34mINFO    [0m Added [33mANSIBLE_ROLES_PATH[0m=[35m/Users/me/.cache/ansible-compat/c52416/[0m[95mroles[0m:[35m/Users/me/.ansible/[0m[95mroles[0m:[35m/usr/share/ansible/[0m[95mroles[0m:[35m/etc/ansible/[0m[95mroles[0m
[1;31mERROR   [0m Computed fully qualified role name of my_new_role does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: [4;94mhttps://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations[0m
Role: [4;94mhttps://galaxy.ansible.com/docs/contributing/creating_role.html#role-names[0m

As an alternative, you can add [32m'role-name'[0m to either skip_list or warn_list.

Traceback (most recent call last):
  File "/Users/me/path/to/ansibroken/venv/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/molecule/command/create.py", line 121, in create
    base.execute_cmdline_scenarios(scenario_name, args, command_args)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/molecule/command/base.py", line 111, in execute_cmdline_scenarios
    scenario.config.runtime.prepare_environment()
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/ansible_compat/runtime.py", line 255, in prepare_environment
    self._install_galaxy_role(self.project_dir, ignore_errors=True)
  File "/Users/me/path/to/ansibroken/venv/lib/python3.9/site-packages/ansible_compat/runtime.py", line 396, in _install_galaxy_role
    raise InvalidPrerequisiteError(msg)
ansible_compat.errors.InvalidPrerequisiteError: Computed fully qualified role name of my_new_role does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.

+ molecule list
[34mINFO    [0m [2;36mRunning [0m[2;32mdefault[0m[2;36m > [0m[2;32mlist[0m
                ╷             ╷                  ╷               ╷         ╷            
 [1m [0m[1mInstance Name[0m[1m [0m│[1m [0m[1mDriver Name[0m[1m [0m│[1m [0m[1mProvisioner Name[0m[1m [0m│[1m [0m[1mScenario Name[0m[1m [0m│[1m [0m[1mCreated[0m[1m [0m│[1m [0m[1mConverged[0m[1m [0m 
╶───────────────┼─────────────┼──────────────────┼───────────────┼─────────┼───────────╴
  instance      │ docker      │ ansible          │ default       │ false   │ false      
                ╵             ╵                  ╵               ╵         ╵            
```

**Comment by apatard** [comment]
oh right. The init command should rather be something like
```
molecule init role mynamespace.my_new_role --driver-name docker
```

and it should mention to edit the ``meta/main.yml`` to properly configure the role information to set the namespace / author to avoid the error in ``molecule create``.
