### ISSUE TITLE
Code examples in documentation are not rendered

### ISSUE THREAD

**Issue by radek-sprta** [ansible-community/molecule#3405]
# Issue Type

- Bug report

# Desired Behavior

Documentation at https://molecule.readthedocs.io/en/latest/configuration.html is properly rendered.

# Actual Behaviour

The code examples at https://molecule.readthedocs.io/en/latest/configuration.html (and other parts of documentation) are missing.

**Comment by steven-cd** [comment]
I had a lot of trouble understanding what exactly molecule was for and how it worked until I found this issue and realised the docs were broken and had several parts missing.

This seems to be because the builds on Readthedocs are raising several warnings (although they still pass) along the lines of:

```
WARNING: autodoc: failed to import class 'config.Config' from module 'molecule'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/molecule/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/molecule/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/molecule/envs/latest/lib/python3.7/site-packages/molecule/config.py", line 32, in <module>
    from molecule import api, interpolation, platforms, scenario, state, util
  File "/home/docs/checkouts/readthedocs.org/user_builds/molecule/envs/latest/lib/python3.7/site-packages/molecule/api.py", line 11, in <module>
    from molecule.verifier.base import Verifier  # noqa
  File "/home/docs/checkouts/readthedocs.org/user_builds/molecule/envs/latest/lib/python3.7/site-packages/molecule/verifier/base.py", line 26, in <module>
    from molecule import util
  File "/home/docs/checkouts/readthedocs.org/user_builds/molecule/envs/latest/lib/python3.7/site-packages/molecule/util.py", line 40, in <module>
    from molecule.app import app
  File "/home/docs/checkouts/readthedocs.org/user_builds/molecule/envs/latest/lib/python3.7/site-packages/molecule/app.py", line 13, in <module>
    app = App()
  File "/home/docs/checkouts/readthedocs.org/user_builds/molecule/envs/latest/lib/python3.7/site-packages/molecule/app.py", line 10, in __init__
    self.runtime = Runtime(isolated=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/molecule/envs/latest/lib/python3.7/site-packages/ansible_compat/runtime.py", line 84, in __init__
    self.config = AnsibleConfig()
  File "/home/docs/checkouts/readthedocs.org/user_builds/molecule/envs/latest/lib/python3.7/site-packages/ansible_compat/config.py", line 432, in __init__
    ["ansible-config", "dump"], universal_newlines=True, env=env
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ansible-config': 'ansible-config'
```

I think this seems to be because ansible-config is not installed - earlier on in the build there is the warning `WARNING: molecule 3.6.1.dev2 does not provide the extra 'ansible-core'`.

This is because `.readthedocs.yml` specifies `ansible-core` in `extra_requires`, but the name of the extra is `ansible-base`. Replace that line with `ansible-base`, and the code examples are rendered again (https://steven-cd-molecule.readthedocs.io/en/3405-rtd-examples/configuration.html). That doesn't seem the best way to fix the problem though, since that extra is duplicated and planned to be removed in #3395 . I don't know enough about RTD to know if there's a better way to address it though.

**Comment by isuftin** [comment]
Is that why everything looks like this? 

<img width="891" alt="image" src="https://user-images.githubusercontent.com/928288/154152242-28f18e74-6652-4b25-b546-5e9026cef574.png">

I thought y'all were just terrible at documentation :D
