### ISSUE TITLE
Can't get my role to run locally anymore (OSError: [Errno 22] Invalid argument)

### ISSUE THREAD

**Issue by geerlingguy** [ansible-community/molecule#3495]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible [core 2.12.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/jgeerling/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jgeerling/Library/Python/3.8/lib/python/site-packages/ansible
  ansible collection location = /Users/jgeerling/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/jgeerling/Library/Python/3.8/bin/ansible
  python version = 3.8.9 (default, Feb 18 2022, 07:45:33) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.0.3
  libyaml = False
molecule 3.6.1 using python 3.9 
    ansible:2.12.3
    delegated:3.6.1 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

N/A, run locally on macOS 12.3.1

# Desired Behavior

If I run `molecule test` inside one of my Ansible roles, I can run `molecule test` successfully.

# Actual Behaviour

```
$ git clone https://github.com/geerlingguy/ansible-role-docker.git
$ molecule test
$ molecule test
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Performing prerun...
INFO     Set ANSIBLE_LIBRARY=/Users/jgeerling/.cache/ansible-compat/320470/modules:/Users/jgeerling/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/Users/jgeerling/.cache/ansible-compat/320470/collections:/Users/jgeerling/.ansible/collections:/usr/share/ansible/collections
INFO     Set ANSIBLE_ROLES_PATH=/Users/jgeerling/.cache/ansible-compat/320470/roles:/Users/jgeerling/Dropbox/VMs/roles
Traceback (most recent call last):
  File "/opt/homebrew/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/molecule/command/test.py", line 161, in test
    base.execute_cmdline_scenarios(scenario_name, args, command_args, ansible_args)
  File "/opt/homebrew/lib/python3.9/site-packages/molecule/command/base.py", line 111, in execute_cmdline_scenarios
    scenario.config.runtime.prepare_environment(install_local=True)
  File "/opt/homebrew/lib/python3.9/site-packages/ansible_compat/runtime.py", line 334, in prepare_environment
    self._install_galaxy_role(self.project_dir, ignore_errors=True)
  File "/opt/homebrew/lib/python3.9/site-packages/ansible_compat/runtime.py", line 494, in _install_galaxy_role
    if not exists or os.readlink(link_path) != str(target):
OSError: [Errno 22] Invalid argument: '/Users/jgeerling/Dropbox/VMs/roles/geerlingguy.docker'
```

I have my global Ansible roles directory symlinked to `/Users/jgeerling/Dropbox/VMs/roles` for convenience:

```
$ ls -lah /etc/ansible/roles
lrwxr-xr-x  1 root  wheel    34B Mar 22 15:01 /etc/ansible/roles -> /Users/jgeerling/Dropbox/VMs/roles
```

And in my case, I have my roles checked out to directories matching the galaxy names (e.g. `geerlingguy.docker` insteaad of `ansible-role-docker`), but that doesn't seem to matter, as the same failure occurs if I check out the role into any directory on my system.

**Comment by geerlingguy** [comment]
Testing other versions:

  - Molecule 3.0.8 ✅
  - Molecule 3.2.0 ✅
  - Molecule 3.4.0 ✅
  - Molecule 3.5.2 ✅
  - Molecule 3.6.0 ✅
  - Molecule 3.6.1 ❌

**Comment by geerlingguy** [comment]
Just realized my `ansible` executable was somehow installed in my system Python (under user/library), so I uninstalled and reinstalled in the correct Python 3.9 path.

Still not able to get Molecule 3.6.1 to work (same error).

**Comment by zhan9san** [comment]
Hi @geerlingguy 

I am glad to help you.

Would you mind giving me more detailed information?

I cannot reproduce this issue.

Here is what I tried.

```shell
❯ python -V
Python 3.9.7

❯ pip freeze | grep molecule
molecule==3.6.1
molecule-docker==1.1.0

❯ ansible-galaxy collection list

# /Users/jackzhang/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.docker  2.3.0
community.general 4.7.0

❯ ls -lah /etc/ansible/roles
lrwxr-xr-x  1 root  wheel    30B Apr  6 10:53 /etc/ansible/roles -> /Users/jackzhang/src/tmp/roles
```

Run test

```shell
❯ pwd
/Users/jackzhang/src/tmp/roles/geerlingguy.docker

❯ molecule --debug -v test
DEBUG    Validating schema /Users/jackzhang/src/tmp/roles/geerlingguy.docker/molecule/default/molecule.yml.
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Performing prerun...
INFO     Set ANSIBLE_LIBRARY=/Users/jackzhang/.cache/ansible-compat/71365d/modules:/Users/jackzhang/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/Users/jackzhang/.cache/ansible-compat/71365d/collections:/Users/jackzhang/.ansible/collections:/usr/share/ansible/collections
INFO     Set ANSIBLE_ROLES_PATH=/Users/jackzhang/.cache/ansible-compat/71365d/roles:/Users/jackzhang/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
INFO     Using /Users/jackzhang/.ansible/roles/geerlingguy.docker symlink to current repository in order to enable Ansible to find the role using its expected full name.
INFO     Running default > dependency
WARNING  Skipping, missing the requirements file.
WARNING  Skipping, missing the requirements file.
INFO     Running default > lint
INFO     Lint is disabled.
INFO     Running default > cleanup
WARNING  Skipping, cleanup playbook not configured.
```

**Comment by geerlingguy** [comment]
I'm guessing there's some weird issue with molecule resolving system paths that was introduced in 3.6.1 (that was not present in 3.6.0 and below.

Steps to reproduce on my own system:

```
 10:11:26 ~/Downloads $ git clone git@github.com:geerlingguy/ansible-role-containerd    
Cloning into 'ansible-role-containerd'...

 10:11:26 ~/Downloads $ cd ansible-role-containerd 

 10:11:29 ~/Downloads/ansible-role-containerd $ molecule test
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Performing prerun...
INFO     Set ANSIBLE_LIBRARY=/Users/jgeerling/.cache/ansible-compat/f490ee/modules:/Users/jgeerling/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/Users/jgeerling/.cache/ansible-compat/f490ee/collections:/Users/jgeerling/.ansible/collections:/usr/share/ansible/collections
INFO     Set ANSIBLE_ROLES_PATH=/Users/jgeerling/.cache/ansible-compat/f490ee/roles:/Users/jgeerling/Dropbox/VMs/roles
Traceback (most recent call last):
  File "/opt/homebrew/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/molecule/command/test.py", line 161, in test
    base.execute_cmdline_scenarios(scenario_name, args, command_args, ansible_args)
  File "/opt/homebrew/lib/python3.9/site-packages/molecule/command/base.py", line 111, in execute_cmdline_scenarios
    scenario.config.runtime.prepare_environment(install_local=True)
  File "/opt/homebrew/lib/python3.9/site-packages/ansible_compat/runtime.py", line 334, in prepare_environment
    self._install_galaxy_role(self.project_dir, ignore_errors=True)
  File "/opt/homebrew/lib/python3.9/site-packages/ansible_compat/runtime.py", line 494, in _install_galaxy_role
    if not exists or os.readlink(link_path) != str(target):
OSError: [Errno 22] Invalid argument: '/Users/jgeerling/Dropbox/VMs/roles/geerlingguy.containerd'
```

The folder `/Users/jgeerling/Dropbox/VMs/roles/geerlingguy.containerd` exists, and is readable. My Ansible configuration has the following roles_path:

```
roles_path = ~/Dropbox/VMs/roles
```

And so my guess is something inside `_install_galaxy_role` is checking the path for `geerlingguy.containerd` (in this case—but same if I run the test in another role on my system), and for some reason bailing out (on `if not exists or os.readlink(link_path) != str(target):`).

**Comment by zhan9san** [comment]
Yes, it is similar to [https://github.com/ansible/ansible-compat/issues/97](https://github.com/ansible/ansible-compat/issues/97).

## root cause

The root cause is there is a conflict between the role installed by `ansible-galaxy` and the role generated by `molecule`, which are in the same role path.

Molecule tried to create a symlink under the role path, but after the `ansible-galaxy` installation, `geerlingguy.containerd` is created as a directory.

No matter customized role path is defined,  this issue can be reproduced by

```shell
$ cd ~/Downloads
$ ansible-galaxy role install geerlingguy.containerd
$ git clone git@github.com:geerlingguy/ansible-role-containerd
$ cd ansible-role-containerd
$ molecule test
```

## workaround

Define a different [role path environment variable0[https://docs.ansible.com/ansible/latest/reference_appendices/config.html#envvar-ANSIBLE_ROLES_PATH] before running `molecule` if both the role installed by `ansible-galaxy` or the role generated by `molecule`.

```shell
$ export ANSIBLE_ROLES_PATH=~/.ansible/molecule/roles
$ cd ~/Downloads/ansible-role-containerd
$ molecule test
```

## follow up

I think this scenario need to be considered in `ansible-compat`. It is useful if role developer wants to installed a stable role from galaxy and develop/test the role by molecule. I would try to create a PR to fix it.

**Comment by zhan9san** [comment]
This is related to #3464  and [#3409 Fix prepare_environment call for role installs](https://github.com/ansible-community/molecule/pull/3409/files#r802489585)

I'll try to fix it, but it may take some time.
