### ISSUE TITLE
ModuleNotFoundError: No module named 'ansiblelint.prerun'

### ISSUE THREAD

**Issue by opeco17** [ansible-community/molecule#3498]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible [core 2.12.4]
  config file = None
  configured module search path = ['/Users/opeco17/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/opeco17/workspace/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/opeco17/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/opeco17/workspace/venv/bin/ansible
  python version = 3.9.7 (default, Sep  3 2021, 12:45:31) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.1.1
  libyaml = True
molecule 3.4.0 using python 3.9 
    ansible:2.12.4
    delegated:3.4.0 from molecule
    docker:0.2.4 from molecule_docker
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

`molecule create` command should work without errors

# Actual Behaviour

When I tried to run `molecule create` command, following error occured

```
Traceback (most recent call last):
  File "/Users/opeco17/workspace/venv/bin/molecule", line 5, in <module>
    from molecule.__main__ import main
  File "/Users/opeco17/workspace/venv/lib/python3.9/site-packages/molecule/__main__.py", line 22, in <module>
    from molecule.shell import main
  File "/Users/opeco17/workspace/venv/lib/python3.9/site-packages/molecule/shell.py", line 29, in <module>
    from molecule import command, logger
  File "/Users/opeco17/workspace/venv/lib/python3.9/site-packages/molecule/command/__init__.py", line 27, in <module>
    from molecule.command import base  # noqa
  File "/Users/opeco17/workspace/venv/lib/python3.9/site-packages/molecule/command/base.py", line 31, in <module>
    from ansiblelint.prerun import prepare_environment
ModuleNotFoundError: No module named 'ansiblelint.prerun'
```

Because ansible-lint with version 6.0.0 and greater doesn't have `prerun` module, it's necessary to add a restriction to ansible-lint version like following.

```
ansible-lint >= 5.1.1 < 6.0.0
```

**Comment by ziegenberg** [comment]
This is now fixed with #3499.
