### ISSUE TITLE
* community.docker:>=3.0.0-a2 (direct request)

### ISSUE THREAD

**Issue by hylaride** [ansible-community/molecule#3622]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
```

```
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/Users/christopher/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/christopher/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/christopher/.pyenv/shims/versions/3.9.9/bin/ansible
  python version = 3.9.9 (main, Feb  7 2022, 15:13:51) [Clang 13.0.0 (clang-1300.0.29.30)]
  jinja version = 3.1.2
  libyaml = True
molecule 4.0.0 using python 3.9 
    ansible:2.13.1
    delegated:4.0.0 from molecule
    docker:2.0.0 from molecule_docker requiring collections: community.docker>=3.0.0-a2
```

Molecule installation method (one of):

- source
- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

I specifically installed molecule-docker 2.0.0.

I would like molecule to run with with molecule-docker 2.0.0.  I'm doing this so that I can specify the platform so that I can run x86 containers on my m1 Mac.

# Actual Behaviour

```
INFO     Running ansible-galaxy collection install -v community.docker:>=3.0.0-a2
WARNING  Retrying execution failure 1 of: ansible-galaxy collection install -v community.docker:>=3.0.0-a2
ERROR    Command returned 1 code:
No config file found; using defaults
Starting galaxy collection install process
Process install dependency map

ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* community.docker:>=3.0.0-a2 (direct request)

Traceback (most recent call last):
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/molecule/command/dependency.py", line 91, in dependency
    base.execute_cmdline_scenarios(scenario_name, args, command_args)
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/molecule/command/base.py", line 121, in execute_cmdline_scenarios
    execute_scenario(scenario)
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/molecule/command/base.py", line 165, in execute_scenario
    execute_subcommand(scenario.config, action)
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/molecule/command/base.py", line 154, in execute_subcommand
    return command(config).execute(args)
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/molecule/logger.py", line 188, in wrapper
    rt = func(*args, **kwargs)
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/molecule/command/dependency.py", line 74, in execute
    self._config.dependency.execute()
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/molecule/dependency/ansible_galaxy/__init__.py", line 76, in execute
    invoker.execute()
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/molecule/dependency/ansible_galaxy/base.py", line 120, in execute
    super().execute()
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/molecule/dependency/base.py", line 92, in execute
    self._config.runtime.require_collection(name, version)
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/ansible_compat/runtime.py", line 398, in require_collection
    self.install_collection(f"{name}:>={version}")
  File "/Users/christopher/.pyenv/shims/versions/3.9.9/lib/python3.9/site-packages/ansible_compat/runtime.py", line 222, in install_collection
    raise InvalidPrerequisiteError(msg)
ansible_compat.errors.InvalidPrerequisiteError: Command returned 1 code:
No config file found; using defaults
Starting galaxy collection install process
Process install dependency map

ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* community.docker:>=3.0.0-a2 (direct request)

make: *** [dependency] Error 1

```

**Comment by hylaride** [comment]
Nevermind.  Had to add the community.docker collection.
