### ISSUE TITLE
Molecule can't find docker process on mac with latest docker desktop 4.13.0 version, due to lack of docker.sock symlink

### ISSUE THREAD

**Issue by CameronMcAuley** [ansible-community/molecule#3705]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version

ansible [core 2.13.5]
  config file = None
  configured module search path = ['/Users/cameronmc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/cameronmc/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.8 (main, Oct 13 2022, 10:18:28) [Clang 13.0.0 (clang-1300.0.29.30)]
  jinja version = 3.1.2
  libyaml = False
molecule 4.0.2 using python 3.10
    ansible:2.13.5
    delegated:4.0.2 from molecule
    docker:2.1.0 from molecule_docker requiring collections: community.docker>=3.0.2 ansible.posix>=1.4.0

OS: macOS Big Sur Version 11.6
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

- ansible-lint
- docker

# Desired Behavior

1. Install molecule and molecule-docker via pip on OSX
2. Install latest version of Docker Desktop on OSX, and run it
3. Create a basic ansible role with `molecule init role acme.my_new_role --driver-name docker`
4. Test the role with `molecule test`
5. molecule should find that docker is running and create the container

# Actual Behaviour

- The latest version of Docker Desktop (4.13.0) has the following release notes:
```By default Docker will not create the /var/run/docker.sock symlink on the host and use the docker-desktop CLI context instead.```
(see: https://docs.docker.com/desktop/release-notes/)
- An important note is that this only seems to be an issue with a **fresh install of docker desktop.** If you upgrade your current version from 4.12.0 to 4.13.0 it seems the location of docker.sock does not change.
- Molecule can not find `/var/run/docker.sock` as it is instead located at `/Users/<USER>/.docker/run/docker.sock` (i.e there was no symlink created). Therefore the following exception occurs when running `molecule test`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory
```

# How I resolved

- I uninstalled Docker Desktop 4.13.0 completely. IMPORTANT: You need to uninstall it via the 'Uninstall' button within Docker Desktop app. (Bug Icon on the top menu bar opens 'Troubleshoot' menu, then click uninstall. After this I removed Docker from applications. You need to uninstall via the app as otherwise when you reinstall an older version it will still have this new docker.sock location)
- I installed Docker Desktop 4.12.0. This version creates docker.sock symlink /var/run/docker.sock and therefore molecule finds the docker process.

# What needs to be changed
- I am not certain if this can be resolved in molecule's code or if this is an issue with the `docker` python module version. Molecule installs docker 6.0.0 by default when installed via `pip3 install molecule-docker`. Maybe there is a new version of the docker package that looks at the correct location.
- If  /var/run/docker.sock can not be found, it should instead be searched for at `/Users/<USER>/.docker/run/docker.sock`
- Maybe DOCKER_HOST default could be modified?

**Comment by CameronMcAuley** [comment]
Fixed with docker desktop 4.13.1, closing
