### ISSUE TITLE
Molecule 5.0 Failing on GitHub Action

### ISSUE THREAD

**Issue by dgibbs64** [ansible-community/molecule#3883]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible-7.4.0
molecule-5.0.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior
 Molecule not failing to run.

# Actual Behaviour
Since release of molecule 5.0 my github action is failing with the following error:
https://github.com/dgibbs64/ansible-role-linux_admin_packages/actions/runs/4759492512/jobs/8458829447

Traceback (most recent call last):
  File "/home/runner/.local/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 165[9](https://github.com/dgibbs64/ansible-role-linux_admin_packages/actions/runs/4759492512/jobs/8458829447#step:5:10), in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/.local/lib/python3.[10](https://github.com/dgibbs64/ansible-role-linux_admin_packages/actions/runs/4759492512/jobs/8458829447#step:5:11)/site-packages/molecule/command/test.py", line [11](https://github.com/dgibbs64/ansible-role-linux_admin_packages/actions/runs/4759492512/jobs/8458829447#step:5:12)3, in test
    base.execute_cmdline_scenarios(scenario_name, args, command_args, ansible_args)
  File "/home/runner/.local/lib/python3.10/site-packages/molecule/command/base.py", line 94, in execute_cmdline_scenarios
    get_configs(args, command_args, ansible_args, glob_str),
  File "/home/runner/.local/lib/python3.10/site-packages/molecule/command/base.py", line 185, in get_configs
    configs = [
  File "/home/runner/.local/lib/python3.10/site-packages/molecule/command/base.py", line 186, in <listcomp>
    config.Config(
  File "/home/runner/.local/lib/python3.10/site-packages/molecule/config.py", line 64, in __call__
    obj.after_init()
  File "/home/runner/.local/lib/python3.10/site-packages/molecule/config.py", line 1[16](https://github.com/dgibbs64/ansible-role-linux_admin_packages/actions/runs/4759492512/jobs/8458829447#step:5:17), in after_init
    self.config = self._reget_config()
  File "/home/runner/.local/lib/python3.10/site-packages/molecule/config.py", line 306, in _reget_config
    env = util.merge_dicts(os.environ, self.env)
  File "/home/runner/.local/lib/python3.10/site-packages/molecule/config.py", line 201, in env
    "MOLECULE_INSTANCE_CONFIG": self.driver.instance_config,
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/runner/.local/lib/python3.10/site-packages/molecule/config.py", line [18](https://github.com/dgibbs64/ansible-role-linux_admin_packages/actions/runs/4759492512/jobs/8458829447#step:5:19)5, in driver
    driver = api.drivers(config=self)[driver_name]
  File "/home/runner/.local/lib/python3.10/site-packages/molecule/api.py", line [30](https://github.com/dgibbs64/ansible-role-linux_admin_packages/actions/runs/4759492512/jobs/8458829447#step:5:31), in __getitem__
    return self.__dict__[i]
KeyError: 'docker'

**Comment by kmezynski** [comment]
I could have observed the same bug on my GitHub action: https://github.com/kmezynski/ansible-role-ohmyzsh/actions/runs/4756760785/jobs/8452737921. No changes to the role itself were made since last successful build.

**Comment by ssbarnea** [comment]
PRs are more than welcomed ;)

**Comment by vitabaks** [comment]
oops

https://github.com/vitabaks/postgresql_cluster/actions/runs/4760126337

![image](https://user-images.githubusercontent.com/37010174/233610002-88e862e3-4b63-4de6-a184-f5403f5a8c8e.png)

**Comment by ktdreyer** [comment]
The original reporter had a GitHub Action that ran `pip install molecule[docker]`. This no longer works in Molecule 5.0.

The same is true for the `podman` driver. This used to work:
```
pip install install molecule[podman]==4.0.4
```

This no longer works in 5.0.0:
```
pip install install molecule[podman]==5.0.0
WARNING: molecule 5.0.0 does not provide the extra 'podman'
```
The replacement is [documented](https://molecule.readthedocs.io/installation/#pip):
```
pip install molecule-plugins[podman]
```

It would be nice if the error message was clearer instead of simply raising `KeyError`. If you raise `MoleculeDriverNotFound` (maybe with a link to the Molecule installation docs) it would be easier for users to search with Google.

**Comment by fauust** [comment]
I was also impacted by this today and here is a proposition to make it clear in the documentation (https://github.com/ansible-community/molecule/pull/3899).

**Comment by dgibbs64** [comment]
So to confirm the fix is to change `molecule[docker]` to `molecule-plugins` in my github action. 

It would be good to have some sort of error message when the failure happens
