### ISSUE TITLE
`molecule` broken with latest version of `ansible-compat`

### ISSUE THREAD

**Issue by mcdonnnj** [ansible-community/molecule#3903]
# Issue Type

- Bug report

# Molecule and Ansible details

```console
$ ansible --version && molecule --version
ansible [core 2.13.9]
  config file = None
  configured module search path = ['/home/mcdonnnj/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/ansible
  ansible collection location = /home/mcdonnnj/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mcdonnnj/.pyenv/versions/ansible-role-docker/bin/ansible
  python version = 3.11.3 (main, Apr 10 2023, 14:31:58) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
molecule 5.0.0 using python 3.11
    ansible:2.13.9
    azure:23.4.1 from molecule_plugins
    containers:23.4.1 from molecule_plugins requiring collections: ansible.posix>=1.3.0 community.docker>=1.9.1 containers.podman>=1.8.1
    delegated:5.0.0 from molecule
    docker:23.4.1 from molecule_plugins requiring collections: community.docker>=3.0.2 ansible.posix>=1.4.0
    ec2:23.4.1 from molecule_plugins
    gce:23.4.1 from molecule_plugins requiring collections: google.cloud>=1.0.2 community.crypto>=1.8.0
    podman:23.4.1 from molecule_plugins requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
    vagrant:23.4.1 from molecule_plugins
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

`molecule test` should successfully perform testing.

# Actual Behaviour

```console
Traceback (most recent call last):
  File "/home/mcdonnnj/.pyenv/versions/ansible-role-docker/bin/molecule", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/molecule/command/test.py", line 113, in test
    base.execute_cmdline_scenarios(scenario_name, args, command_args, ansible_args)
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/molecule/command/base.py", line 119, in execute_cmdline_scenarios
    execute_scenario(scenario)
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/molecule/command/base.py", line 162, in execute_scenario
    execute_subcommand(scenario.config, action)
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/molecule/command/base.py", line 152, in execute_subcommand
    return command(config).execute(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/molecule/logger.py", line 189, in wrapper
    rt = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/molecule/command/dependency.py", line 40, in execute
    self._config.dependency.execute()
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/molecule/dependency/ansible_galaxy/__init__.py", line 75, in execute
    invoker.execute()
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/molecule/dependency/ansible_galaxy/base.py", line 129, in execute
    self.execute_with_retries()
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/molecule/dependency/base.py", line 55, in execute_with_retries
    util.run_command(self._sh_command, debug=self._config.debug, check=True)
  File "/home/mcdonnnj/.pyenv/versions/3.11.3/envs/ansible-role-docker/lib/python3.11/site-packages/molecule/util.py", line 149, in run_command
    result = app.runtime.exec(
             ^^^^^^^^^^^^^^^^
AttributeError: 'Runtime' object has no attribute 'exec'
```

This is likely caused by  https://github.com/ansible-community/molecule/blob/0d874bd9ccacda8df5e110020454764a6b9b908d/src/molecule/util.py#L149 not being updated for https://github.com/ansible/ansible-compat/pull/256 which was included in [ansible-compat v4.0.1](https://github.com/ansible/ansible-compat/releases/tag/v4.0.1).

**Comment by danielpodwysocki** [comment]
+1 , just ran into it.

**Comment by danielpodwysocki** [comment]
Btw. do the dependencies work as expected for us here?

 https://github.com/ansible-community/molecule/tree/main/.config

Looks like we should be locked to `3.0.2` ?

**Comment by zenzedoon** [comment]
i have the same issue : i have molecule v 5.0.0 with poython v 3.10 , absible core 2.14.5 , when i try to create new ansible role i got this error: 
molecule init role acme.testrole
INFO     Initializing new role testrole...
Traceback (most recent call last):
  File "/home/zenzedoon/.local/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/zenzedoon/.local/lib/python3.10/site-packages/molecule/command/init/role.py", line 174, in role
    r.execute()
  File "/home/zenzedoon/.local/lib/python3.10/site-packages/molecule/command/init/role.py", line 84, in execute
    result = util.run_command(cmd)
  File "/home/zenzedoon/.local/lib/python3.10/site-packages/molecule/util.py", line 149, in run_command
    result = app.runtime.exec(
AttributeError: 'Runtime' object has no attribute 'exec'

**Comment by isuftin** [comment]
Reverting from ansible-compat 4.0.1 to 3.0.2 fixed the issue for me.

**Comment by gannaramu** [comment]
+1 ran into the same issue.

**Comment by dvzrv** [comment]
I am running into this issue as well trying to package molecule 5.0.0 for Arch Linux (all related tests fail).

Judging from https://github.com/ansible/ansible-compat/releases/tag/v4.0.1 I guess this PR is at fault https://github.com/ansible/ansible-compat/pull/256

@ssbarnea a more descriptive message as to why that has been done and a more concerted action in regards to the consumers of ansible-compat would have been great.

**Comment by pimvh** [comment]
I just started using this awesome package, and I really like it, i just want to improve it.

This the second time version 5.0.0 introduced plain breaking changes (lint being removed too) without guardrails being present.

As a consumer of this package I would like to just rely on a specific versions of `molecule` and `molecule-plugins[...]` and not care explicitly about underlying versions.

My suggestion would be to explicitly pin the requirements of this package. I would be happy to contribute if people can point me in the right direction.

Additionally, is a lot of refactoring going on which might explain these breaking changes? Is there a roadmap somewhere which I can consult? It would be nice to get an idea of the direction.

**Comment by ssbarnea** [comment]
5.0.1 fixes that

**Comment by dvzrv** [comment]
For system packaging this is still problematic with molecule 5.0.1 and ansible-compat 4.0.1 without [this](https://github.com/ansible-community/molecule/pull/3904) so I'd rather wait for a proper fix to this.

```
=========================== short test summary info ============================
FAILED ../../../../dev/test_util.py::test_run_command - AttributeError: 'Runt...
FAILED ../../../../dev/test_util.py::test_run_command_with_debug - AttributeE...
FAILED ../../../../dev/test_util.py::test_run_command_baked_cmd_env - Attribu...
FAILED ../../../../dev/test_util.py::test_run_command_with_debug_handles_no_env
FAILED ../../../../dev/command/test_base.py::test_command_completion[bash] - ...
FAILED ../../../../dev/command/test_base.py::test_command_completion[zsh] - A...
FAILED ../../../../dev/command/test_base.py::test_command_completion[fish] - ...
FAILED ../../../../dev/command/init/test_role.py::test_execute - AttributeErr...
FAILED ../../../../dev/command/init/test_role.py::test_execute_role_exists - ...
FAILED ../../../../dev/cookiecutter/test_molecule.py::test_valid - AttributeE...
FAILED ../../../../dev/model/v2/test_schema.py::test_molecule_schema - Attrib...
======= 11 failed, 424 passed, 7 skipped, 1 xfailed, 3 warnings in 5.22s =======
```

**Comment by lkiesow** [comment]
The problem popped up again and many people will likely get hit by this due to the latest version of `ansible-lint` requiring a new version of `ansible-compat`. Installing `molecule` and `ansible-lint` both is very common and right now, `ansible-lint`'s dependencies will win and `pip` will automatically install `molecule==5.0.0`:

```
❯ pip install ansible-lint molecule
❯ pip freeze                       
…
molecule==5.0.0
…
❯ pip install -U molecule
…
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ansible-lint 6.17.0 requires ansible-compat>=4.0.5, but you have ansible-compat 3.0.2 which is incompatible.
```

This means that even with Molecule 5.0.1 released, many people will run into this issue, and you need manual intervention to fix this.

**Comment by ziegenberg** [comment]
#3904 will fix it finally for good.

**Comment by lkiesow** [comment]
You can just install Molecule 5.0.1 specifically. Pip will then resole the modules and install an older version of ansible-lint:

```
❯ pip install ansible-lint molecule==5.0.1
```
